---
- hosts: all
  become: true
  vars:
    selinux_state: disabled
  roles:
    - epel_repositories
    - selinux

- hosts: all
  become: true
  vars:
    foreman_admin_password: changeme
  pre_tasks:
    - include_vars:
        file: certs.yml
      failed_when: false
    - include_vars:
        file: ssh_keys.yml
      failed_when: false
  roles:
    - foreman_ca
    - foreman_certs
    - foreman_repositories
    - foreman_postgresql
    - foreman
    - foreman_apache
    - foreman_proxy
    - foreman_setup
