---
- hosts: localhost
  vars:
    url: "https://{{ ansible_fqdn }}/api/v2/hosts"
    data:
      host:
        name: "{{ ansible_fqdn }}"
        location_id: 2
        organization_id: 1
        ip: "{{ ansible_default_ipv4.address }}"
        build: false
        managed: false
  tasks:
    - name: "register unmanaged host"
      uri:
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        method: POST
        return_content: yes
        timeout: 3
        user: admin
        password: "{{ foreman_admin_password }}"
        validate_certs: false
        url: "{{ url }}"
        body: "{{ data | to_json }}"
      register: registration_result
      until: (registration_result.json is defined) and (registration_result.status == 422 or registration_result.status == 200)
      retries: 300
      delay: 4
      ignore_errors: true

    - fail:
        msg: "{{ registration_result }}"
      when: registration_result.status != 422 and registration_result.status != 200
