---
- name: "register smart proxy"
  uri:
    force_basic_auth: yes
    headers:
      Content-Type: "application/json"
    method: POST
    return_content: yes
    timeout: 3
    user: admin
    password: "{{ foreman_admin_password }}"
    validate_certs: false
    url: "{{ foreman_proxy_register_foreman_url }}"
    body: "{{ foreman_proxy_register_data | to_json }}"
  register: registration_result
  until: registration_result.status == 422 or registration_result.status == 201
  retries: 300
  delay: 4
  failed_when: registration_result.status != 422 and registration_result.status != 201
